#!/bin/bash

ufw enable


apt update -q && apt upgrade -yq

# system utils
apt install -yq --no-install-recommends \
	gparted \
	exfat-utils \
	lvm2 \
	libxml2-utils \
	xdotool \
	curl \
	stow \
	dconf-editor \
        gnome-tweak-tool \
        gnome-shell-extensions \
        gnome-shell-extension-appindicator

# development utils
apt install -yq --no-install-recommends \
	git \
	neovim \
	python3-pip \
	ghc

# media programs
add-apt-repository -yq ppa:inkscape.dev/stable
apt update -q && apt install -yq --no-install-recommends \
	inkscape \
	gimp \
        shotwell \
        vlc \
        rhythmbox \
        rhythmbox-plugins

# productivity
add-apt-repository -yq ppa:phoerious/keepassxc
add-apt-repository -yq ppa:andreasbutti/xournalpp-master
apt update -q && apt install -yq --no-install-recommends \
	keepassxc \
	xournalpp \
	libreoffice-writer \
	libreoffice-calc \
	libreoffice-help-en-us \
	hunspell-de-de \
	libreoffice-grammarcheck-de-de \
	hunspell-en-us \
	libreoffice-grammarcheck-en-us


# set up identification
[ ! -f "$HOME/.ssh/id_ecdsa" ] && ssh-keygen -t ecdsa -f $HOME/.ssh/id_ecdsa -N ""
git config --global user.email "fynn.freyer@googlemail.com"
git config --global user.name "Fynn Freyer"


# set gnome preferences and shortcuts

# minimize/preview windows when clicked in dock
gsettings set \
	org.gnome.shell.extensions.dash-to-dock \
	click-action 'minimize-or-previews'


# set ctrl-alt-x to launch xkill
gsettings set \
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
	name 'Launch xkill'
gsettings set \
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
	command 'xkill'
gsettings set \
        org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
	binding '<Primary><Alt>x'

# set ctrl-alt-delete to launch gnome-system-monitor (and unset logout)
gsettings set \
	org.gnome.settings-daemon.plugins.media-keys \
	logout []
gsettings set \
        org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
        name 'Launch system monitor'
gsettings set \
        org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
        command 'gnome-system-monitor'
gsettings set \
        org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
        binding '<Primary><Alt>Delete'

# nautilus settings
# don't show thumbnails
gsettings set \
	org.gnome.nautilus.preferences \
	show-image-thumbnails 'never'

# show create link option in context menu
gsettings set \
	org.gnome.nautilus.preferences \
	show-create-link true

# don't show a warning in system mon when killing a proc
gsettings set \
	org.gnome.gnome-system-monitor \
	kill-dialog true


reboot
