#!/bin/bash


if [ "$EUID" -ne 0 ]
  then echo "Please run as root"; echo "Computer reboots in the end"
  exit
fi


# enable firewall
ufw enable

# get latest updates
apt update && apt upgrade -y  &>/dev/null

# installing programs
## system utils
apt install -y --no-install-recommends \
	stow \
	gparted \
	exfat-utils \
	cryfs \
	lvm2 \
	libxml2-utils \
	xdotool \
	curl \
	dconf-editor \
        gnome-tweak-tool \
        gnome-shell-extensions \
        gnome-shell-extension-appindicator

# development
apt install -y --no-install-recommends \
	git \
	neovim \
	python3-pip \
	ghc

pip3 install pynvim jedi

snap install pycharm-professional --classic

## media
add-apt-repository ppa:inkscape.dev/stable -y
apt update && apt install -y --no-install-recommends \
	inkscape \
	gimp \
        shotwell \
        vlc \
        rhythmbox \
        rhythmbox-plugins \
	filezilla \
	transmission

## productivity
add-apt-repository ppa:phoerious/keepassxc -y
add-apt-repository ppa:andreasbutti/xournalpp-master -y
apt update && apt install -y --no-install-recommends \
	keepassxc \
	xournalpp \
	libreoffice-writer \
	libreoffice-calc \
	libreoffice-help-en-us \
	hunspell-de-de \
	hunspell-en-us \
	libreoffice-grammarcheck-en-us


# set up identification
[ ! -f "$HOME/.ssh/id_ecdsa" ] && ssh-keygen -t ecdsa -f $HOME/.ssh/id_ -N ""
git config --global user.email "fynn.freyer@googlemail.com"
git config --global user.name "Fynn Freyer"


# set gnome preferences and shortcuts
## minimize/preview windows when clicked in dock
gsettings set \
	org.gnome.shell.extensions.dash-to-dock \
	click-action 'minimize-or-previews'

## set ctrl-alt-x to launch xkill
gsettings set \
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
	name 'Launch xkill'
gsettings set \
	org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
	command 'xkill'
gsettings set \
        org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
	binding '<Primary><Alt>x'

## set ctrl-alt-delete to launch gnome-system-monitor (and unset logout)
gsettings set \
	org.gnome.settings-daemon.plugins.media-keys \
	logout []
gsettings set \
        org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
        name 'Launch system monitor'
gsettings set \
        org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
        command 'gnome-system-monitor'
gsettings set \
        org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ \
        binding '<Primary><Alt>Delete'

## nautilus settings
### don't show thumbnails
gsettings set \
	org.gnome.nautilus.preferences \
	show-image-thumbnails 'never'

### show create link option in context menu
gsettings set \
	org.gnome.nautilus.preferences \
	show-create-link true

## don't show a warning in system mon when killing a proc
gsettings set \
	org.gnome.gnome-system-monitor \
	kill-dialog true


# setup
## download dotfile repo
cd ~
git clone https://github.com/FynnFreyer/.dotfiles.git
cd .dotfiles

## install password db and config
stow passwords

## install secrets
echo manual intervention needed to unlock vpn
mkdir tmp
cryfs vpn tmp
cd tmp

### vpn profiles
ls | xargs -I {} nmcli connection import type openvpn file {}
cd -
cryfs-unmount tmp
rm -d tmp


#reboot
