#!/bin/bash

ufw enable
[ ! -f "$HOME/.ssh/id_ecdsa" ] && ssh-keygen -t ecdsa -f $HOME/.ssh/id_ecdsa -N ""


apt update -q && apt upgrade -yq


# system utils
apt install -yq --no-install-recommends \
	gparted \
	exfat-utils \
	lvm2 \
	libxml2-utils \
	stow \
	dconf-editor \
        gnome-tweak-tool \
        gnome-shell-extensions \
        gnome-shell-extension-appindicator


# development utils
apt install -yq --no-install-recommends \
	git \
	neovim


# artsy stuff
add-apt-repository -yq ppa:inkscape.dev/stable
apt update -q && apt install -yq --no-install-recommends \
	inkscape \
	gimp \
	shotwell

# user progs
add-apt-repository -yq ppa:phoerious/keepassxc
add-apt-repository -yq ppa:andreasbutti/xournalpp-master
apt update -q && apt install -yq --no-install-recommends \
	keepassxc \
	xournalpp \
	libreoffice-writer \
	libreoffice-calc


[ ! -f "$HOME/.ssh/id_ecdsa" ] && ssh-keygen -t ecdsa -f $HOME/.ssh/id_ecdsa -N ""
git config --global user.email "fynn.freyer@googlemail.com"
git config --global user.name "Fynn Freyer"


reboot
